sudo: false
language: ruby
bundler_args: --without beaker
rvm:
  - 2.0
  - 2.1
  - 2.2
env:
  - PUPPET_GEM_VERSION="~> 3.7"
  - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  include:
    - rvm: 2.2
      script: 'bundle exec rake rubocop'
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.7"
  fast_finish: true
notifications:
  email: false
